In [5]:
import bs4 as bs
import re
import pandas as pd
from selenium import webdriver
Names=[]
Prices=[]
Links=[]
url="https://www.paklap.pk/laptops-prices.html?product_list_limit=all"
driver = webdriver.Chrome("C:/Users/Usman/Downloads/chromedriver.exe")
driver.get(url)
for i in range(1,121):
    try:
        Name=driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[4]/ol/li["+str(i)+"]/div/div[2]/strong/a")
        Price=driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[1]/div[4]/ol/li["+str(i)+"]/div/div[2]/div[1]/span/span/span")
        Names.append(Name.text)
        Prices.append(Price.text)
        Links.append(Name.get_attribute("href"))
    except:
        1==1
driver.close()
df=pd.DataFrame(list(zip(Names,Prices,Links)),columns=["Name","Price","Links"])
# df.sort_values(["Name","Price"],inplace=True)
df

,Name,Price,Links
0,HP ChromeBook 14 G4 - Intel Celeron 02GB 16GB ...,"Rs. 16,999",https://www.paklap.pk/hp-chromebook-14-g4-lapt...
1,HP ProBook MT31 Mobile Thin Client - Intel Cel...,"Rs. 46,500",https://www.paklap.pk/hp-probook-mt31-intel-ce...
2,HP Chromebook x360 11 G3 EE - Intel Celeron N4...,"Rs. 48,500",https://www.paklap.pk/hpchromebookx360-11-g3.html
3,Lenovo Ideapad 330 - Intel Celeron (4MB Cache)...,"Rs. 52,999",https://www.paklap.pk/lenovo-ideapad-330-celer...
4,HP Engage Go Mobile Tablet PC - 7th Gen Intel ...,"Rs. 54,500",https://www.paklap.pk/hpengagego.html
...,...,...,...
104,"Microsoft Surface Book 3 - Core i7 - 13.5"" Pla...","Rs. 308,900",https://www.paklap.pk/microsoft-surfacebook-3-...
105,Dell G7 7500 15 Gaming Laptop - Comet Lake - 1...,"Rs. 310,000",https://www.paklap.pk/dell-g7-15-7500-2020-gam...
106,Acer Predator Triton 500 - Comet Lake - 10th G...,"Rs. 335,000",https://www.paklap.pk/acer-predator-triton-500...
107,HP ZBook 17 G6 Mobile Workstation - 9th Gen Ci...,"Rs. 390,000",https://www.paklap.pk/hp-zbook-17-g6-core-i7-9...
108,HP ZBook 17 G6 Mobile Workstation - 9th Gen Ci...,"Rs. 415,000",https://www.paklap.pk/hp-zbook-17-g6-core-i7-9...

In [6]:
import bs4 as bs
import re
import pandas as pd
from selenium import webdriver
Names=[]
Prices=[]
Links=[]
driver = webdriver.Chrome("C:/Users/Usman/Downloads/chromedriver.exe")
for j in range(1,11):
    url="https://www.daraz.pk/laptops/?page="+str(j)+"&spm=a2a0e.searchlistcategory.cate_1.5.4c8c5e4eZv4a82"
    driver.get(url)
    for i in range(1,40):
        try:
            Name=driver.find_element_by_xpath("/html/body/div[3]/div/div[3]/div[1]/div/div[1]/div[2]/div["+str(i)+"]/div/div/div[2]/div[2]/a")
            Price=driver.find_element_by_xpath("/html/body/div[3]/div/div[3]/div[1]/div/div[1]/div[2]/div["+str(i)+"]/div/div/div[2]/div[3]/span")
            Names.append(Name.text)
            Prices.append(Price.text)
            Links.append(Name.get_attribute("href"))
        except:
            1==1
driver.close()
df=pd.DataFrame(list(zip(Names,Prices,Links)),columns=["Name","Price","Links"])
# df.sort_values(["Name","Price"],inplace=True)
df

,Name,Price,Links
0,"HP 15S-DU3502TU 11th Gen Core i3, 4GB DDR4 1TB...","Rs. 78,399",https://www.daraz.pk/products/hp-15s-du3502tu-...
1,HP 15-DW3022NIA Laptop - 11th Gen Intel Core i...,"Rs. 98,000",https://www.daraz.pk/products/hp-15-dw3022nia-...
2,"HP 15S-DU2039TX 10th Gen Core i5, 4GB, 1TB HDD...","Rs. 103,500",https://www.daraz.pk/products/hp-15s-du2039tx-...
3,iLife Zed Air X - 13.3: FHD Display - Intel® C...,"Rs. 46,999",https://www.daraz.pk/products/ilife-zed-air-x-...
4,Acer C720 ChromeBook Laptop - 4gb / 16gb - Lon...,"Rs. 14,500",https://www.daraz.pk/products/acer-c720-chrome...
...,...,...,...
385,LENOVO THINKPAD T410 14-inch Notebook 2.40 GHz...,"Rs. 24,500",https://www.daraz.pk/products/lenovo-thinkpad-...
386,HP Probook 6470b 14-inch Notebook 2.50 GHz Int...,"Rs. 32,500",https://www.daraz.pk/products/hp-probook-6470b...
387,DELL LATITUDE E6220 12.5-inch Notebook 2.50 GH...,"Rs. 28,000",https://www.daraz.pk/products/dell-latitude-e6...
388,DELL LATITUDE E6330 13.3-inch Notebook 2.50 GH...,"Rs. 31,000",https://www.daraz.pk/products/dell-latitude-e6...
389,HP Probook 6460b 14-inch Notebook 2.50 GHz Int...,"Rs. 30,000",https://www.daraz.pk/products/hp-probook-6460b...

In [7]:
import bs4 as bs
import re
import pandas as pd
from selenium import webdriver
Names=[]
Prices=[]
Links=[]
driver = webdriver.Chrome("C:/Users/Usman/Downloads/chromedriver.exe")
for j in range(1,13):
    url="https://www.czone.com.pk/laptops-pakistan-ppt.74.aspx?recs=10&page="+str(j)+""
    driver.get(url)
    for i in range(1,10):
        try:
            Name=driver.find_element_by_xpath("/html/body/form/div[3]/div[2]/div[2]/div[4]/div["+str(i)+"]/div/div[1]/div/div[2]/div/div[1]/h4/a")
            Price=driver.find_element_by_xpath("/html/body/form/div[3]/div[2]/div[2]/div[4]/div["+str(i)+"]/div/div[1]/div/div[2]/div/div[2]/div[3]/span")
            Names.append(Name.text)
            Prices.append(Price.text)
            Links.append(Name.get_attribute("href"))
        except:
            1==1
driver.close()
df=pd.DataFrame(list(zip(Names,Prices,Links)),columns=["Name","Price","Links"])
# df.sort_values(["Name","Price"],inplace=True)
df

,Name,Price,Links
0,"Lenovo Ideapad 330 Laptop Intel Celeron N4000,...","Rs.50,900",https://www.czone.com.pk/laptops-lenovo-laptop...
1,Lenovo Ideapad 330 Laptop - Intel Celeron N400...,"Rs.50,990",https://www.czone.com.pk/laptops-lenovo-laptop...
2,Asus E410MA-202.Blue Laptop - Intel Celeron N4...,"Rs.55,900",https://www.czone.com.pk/laptops-asus-laptops-...
3,Lenovo IdeaPad 3 Laptop - Intel Pentium Gold 6...,"Rs.59,500",https://www.czone.com.pk/laptops-lenovo-laptop...
4,"Dell Vostro 14 3401 Laptop - 10th Gen Ci3, 4GB...","Rs.67,000",https://www.czone.com.pk/laptops-dell-laptops-...
...,...,...,...
99,"Microsoft Surface Book 3 15"" 10th Gen Ci7 32GB...","Rs.460,500",https://www.czone.com.pk/laptops-microsoft-lap...
100,"Microsoft Surface Laptop 4 15"" 11th Gen Core i...","Rs.495,000",https://www.czone.com.pk/laptops-microsoft-lap...
101,"Apple MacBook Pro 15.4"" MV942 (Space Gray), 2019","Rs.518,000",https://www.czone.com.pk/laptops-apple-laptops...
102,"Lenovo ThinkPad X1 Fold 13.3"" QXGA Foldable PC...","Rs.593,000",https://www.czone.com.pk/laptops-lenovo-laptop...
103,"Apple MacBook Pro 16"" MVVN2 (Space Gray) - Lat...","Rs.659,000",https://www.czone.com.pk/laptops-apple-laptops...

In [8]:
import bs4 as bs
import re
import pandas as pd
from selenium import webdriver
Names=[]
Prices=[]
Links=[]
driver = webdriver.Chrome("C:/Users/Usman/Downloads/chromedriver.exe")
for j in range(1,4):
    url="https://myshop.pk/laptops-desktops-computers/laptops?p="+str(j)+"&product_list_limit=64"
    driver.get(url)
    for i in range(1,64):
        try:
            Name=driver.find_element_by_xpath("/html/body/div[1]/main/div[3]/div[1]/div[3]/ol/li["+str(i)+"]/div/div[2]/strong/a")
            Price=driver.find_element_by_xpath("/html/body/div[1]/main/div[3]/div[1]/div[3]/ol/li["+str(i)+"]/div/div[2]/div[4]/span/span/span")
            Names.append(Name.text)
            Prices.append(Price.text)
            Links.append(Name.get_attribute("href"))
        except:
            1==1
driver.close()
df=pd.DataFrame(list(zip(Names,Prices,Links)),columns=["Name","Price","Links"])
# df.sort_values(["Name","Price"],inplace=True)
df

,Name,Price,Links
0,Hp Probook 440 G8 i7 :1y,Rs 0.00,https://myshop.pk/hp-probook-440-g8-i7-1y-paki...
1,Lenovo Ideapad 15 330 :1y,"Rs 55,500.00",https://myshop.pk/lenovo-ideapad-15-330-pakist...
2,Lenovo Ideapad 14 V14,,https://myshop.pk/lenovo-ideapad-14-v14-1-paki...
3,Lenovo Ideapad 14 V14,"Rs 59,900.00",https://myshop.pk/lenovo-ideapad-14-v14-2-paki...
4,Lenovo Ideapad 3 14 14IML05,,https://myshop.pk/lenovo-ideapad-3-14-14iml05-...
...,...,...,...
184,Microsoft | Surface Book 3 - 15'' - i7 256GB,"Rs 399,500.00",https://myshop.pk/microsoft-surface-book-3-15-...
185,Lenovo Legion 7-15IMH-81YU004DAX Gaming Laptop,"Rs 409,500.00",https://myshop.pk/lenovo-legion-7-15imh-81yu00...
186,Dell XPS 15 9500,"Rs 409,500.00",https://myshop.pk/dell-xps-15-9500-pakistan.html
187,"Apple | Macbook Pro (2019) - 16"" i7 1TB with T...",,https://myshop.pk/apple-macbook-pro-2019-16-i7...
188,Acer Predator - Triton 500 i7,"Rs 413,100.00",https://myshop.pk/acer-predator-triton-500-i7-...

In [10]:
import bs4 as bs
import re
import pandas as pd
from selenium import webdriver
Names=[]
Prices=[]
Links=[]
url="https://www.telemart.pk/computer/laptops.html"
driver = webdriver.Chrome("C:/Users/Usman/Downloads/chromedriver.exe")
driver.get(url)
for i in range(1,30):
    try:
        Name=driver.find_element_by_xpath("/html/body/div[2]/div[3]/div/div/div[2]/div/div[2]/div[1]/div["+str(i)+"]/a/div[2]/h2/span")
        Price=driver.find_element_by_xpath("/html/body/div[2]/div[3]/div/div/div[2]/div/div[2]/div[1]/div["+str(i)+"]/a/div[2]/div[2]/ins")
        Names.append(Name.text)
        Prices.append(Price.text)
        Links.append(Name.get_attribute("href"))
    except:
        1==1
driver.close()
df=pd.DataFrame(list(zip(Names,Prices,Links)),columns=["Name","Price","Links"])
# df.sort_values(["Name","Price"],inplace=True)
df

Empty DataFrame
Columns: [Name, Price, Links]
Index: []